on:
  workflow_dispatch

permissions:
  contents: read
  
env:
  targetEnv: dev

name: Azure Bicep
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure this secret contains the JSON with clientId, clientSecret, subscriptionId, and tenantId
        auth-type: SERVICE_PRINCIPAL

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=${{ env.targetEnv }}
